modLoader="javafml"
loaderVersion="[45,)"
license="Not specified"

[[mods]]
modId="avaritia"
version="1.5.3"
displayName="Avaritia Lite"
displayURL="https://www.curseforge.com/minecraft/mc-mods/avaritia-lite"
logoFile="logo.png"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Bullfighter, MCreator"

[[dependencies.avaritia]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4]"
    ordering="NONE"
    side="BOTH"




