modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="avaritia"
version="1.9.0"
displayName="Avaritia Lite"
displayURL="https://www.curseforge.com/minecraft/mc-mods/avaritia-lite"
logoFile="logo.png"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Bullfighter, MCreator"

[[dependencies.avaritia]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"



[[dependencies.avaritia]]
    modId="kleidersplayerrenderer"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.avaritia]]
    modId="jei"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

