modLoader="javafml"
loaderVersion="[4,)"
license="Not specified"

[[mods]]
modId="avaritia"
version="1.10.7"
displayName="Avaritia Lite"
displayURL="https://www.curseforge.com/minecraft/mc-mods/avaritia-lite"
logoFile="logo.png"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Bullfighter, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.avaritia]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.65,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.avaritia]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"

[[dependencies.avaritia]]
    modId="kleiders_custom_renderer"
    type="required"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.avaritia]]
    modId="kleidersplayerrenderer"
    type="optional"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.avaritia]]
    modId="jei"
    type="optional"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration