modLoader="javafml"
loaderVersion="[2,)"
license="Not specified"

[[mods]]
modId="avaritia"
version="1.10.1"
displayName="Avaritia Lite"
displayURL="https://www.curseforge.com/minecraft/mc-mods/avaritia-lite"
logoFile="logo.png"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Bullfighter, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.avaritia]]
    modId="neoforge"
    type="required"
    versionRange="[20.4.223,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.avaritia]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.4]"
    ordering="NONE"
    side="BOTH"


[[dependencies.avaritia]]
    modId="jei"
    type="optional"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

